AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation SERVICENOW Data Source Template
Resources:
  DataSourceServiceNow:
    Type: AWS::QBusiness::DataSource
    Properties:
      ApplicationId: app12345-1234-1234-1234-123456789012
      IndexId: indx1234-1234-1234-1234-123456789012
      DisplayName: MyServiceNowDataSource
      RoleArn: arn:aws:iam::123456789012:role/qbusiness-data-source-role
      Configuration:
        type: SERVICENOWV2
        syncMode: FULL_CRAWL
        secretArn: arn:aws:secretsmanager:us-west-2:123456789012:secret:my-servicenow-secret
        enableIdentityCrawler: "true"
        connectionConfiguration:
          repositoryEndpointMetadata:
            hostUrl: mycompany.service-now.com
            authType: basicAuth
            servicenowInstanceVersion: Tokyo
        repositoryConfigurations:
          knowledgeArticle:
            fieldMappings:
              - indexFieldName: article_id
                indexFieldType: STRING
                dataSourceFieldName: id
                dateFieldFormat: yyyy-MM-dd'T'HH:mm:ss'Z'
          attachment:
            fieldMappings:
              - indexFieldName: attachment_id
                indexFieldType: STRING
                dataSourceFieldName: id
                dateFieldFormat: yyyy-MM-dd'T'HH:mm:ss'Z'
          serviceCatalog:
            fieldMappings:
              - indexFieldName: catalog_item_id
                indexFieldType: STRING
                dataSourceFieldName: id
                dateFieldFormat: yyyy-MM-dd'T'HH:mm:ss'Z'
          incident:
            fieldMappings:
              - indexFieldName: incident_id
                indexFieldType: STRING
                dataSourceFieldName: id
                dateFieldFormat: yyyy-MM-dd'T'HH:mm:ss'Z'
        additionalProperties:
          maxFileSizeInMegaBytes: "50"
          isCrawlKnowledgeArticle: "true"
          isCrawlKnowledgeArticleAttachment: "true"
          includePublicArticlesOnly: "false"
          knowledgeArticleFilter: filter_condition
          incidentQueryFilter: incident_condition
          serviceCatalogQueryFilter: service_catalog_condition
          isCrawlServiceCatalog: "true"
          isCrawlServiceCatalogAttachment: "true"
          isCrawlActiveServiceCatalog: "true"
          isCrawlInactiveServiceCatalog: "false"
          isCrawlIncident: "true"
          isCrawlIncidentAttachment: "false"
          isCrawlActiveIncident: "true"
          isCrawlInactiveIncident: "false"
          applyACLForKnowledgeArticle: "true"
          applyACLForServiceCatalog: "true"
          applyACLForIncident: "true"
          incidentStateType:
            - Open
            - Resolved
          knowledgeArticleTitleRegExp: ".*"
          serviceCatalogTitleRegExp: ".*"
          incidentTitleRegExp: ".*"
          inclusionFileTypePatterns:
            - "*.pdf"
            - "*.docx"
          exclusionFileTypePatterns:
            - "*.tmp"
          inclusionFileNamePatterns:
            - important-*
          exclusionFileNamePatterns:
            - temporary-*
          enableDeletionProtection: "false"
          deletionProtectionThreshold: "15"
